services:
  blockchain:
    image: node:alpine
    container_name: blockchain
    ports:
      - "8545:8545"
    volumes:
      - ./blockchain:/app
    command: sh -c "cd /app && npm install && npx hardhat node"

  frontend:
    image: node:alpine
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: sh -c "sleep 10 && cd /app && npm install && node /app/src/BuildingsFront/DeploySmartContract.js && npm run dev"
    depends_on:
      blockchain:
        condition: service_started
        restart: true
